# Not using Python code, it's just a bone for Travis CI
language: python
python: 3.4

sudo: required
env:
  global:
    - |
      DISPLAY=:0.0
      WINEDLLOVERRIDES="mscoree,mshtml="
      PATH=${PATH//:\.\/node_modules\/\.bin/} # Workaround for Travis issue #4862
      CWD="$TRAVIS_BUILD_DIR"
  matrix:
    - DEPOSIT=2000 PAIR=EURUSD YEAR=2014 SPREAD=10 BT=DS
    - DEPOSIT=4000 PAIR=EURUSD YEAR=2014 SPREAD=20 BT=W2
    - DEPOSIT=8000 PAIR=EURUSD YEAR=2015 SPREAD=30 BT=Z3

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.wine

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always

before_install:
  - ulimit -a && free -m

install:
  - sudo $CWD/scripts/provision.sh

before_script:
  - set -e

script:
  - $CWD/scripts/run_backtest.sh -d $DEPOSIT -p $PAIR -y $YEAR -s $SPREAD -b $BT
