language: generic

sudo: required
dist: trusty
env:
  global:
    - |
      PATH=${PATH//:\.\/node_modules\/\.bin/} # Workaround for Travis issue #4862
      CWD="$TRAVIS_BUILD_DIR"
  matrix:
    - TEST_ARGS="-x -f /etc/hosts -h"
    - TEST_ARGS="-v -t -d 1000 -p EURUSD -y 2010 -s 10 -b N0 -e TestSpread -D5"
    - TEST_ARGS="-v -t -d 1000 -p EURUSD -y 2012 -s 10 -b W2"
    - TEST_ARGS="-v -t -d 2000 -p EURUSD -y 2013 -s 20 -b Z3"
    - TEST_ARGS="-v -t -d 3000 -p EURUSD -y 2014 -s 30 -b DS"

matrix:
  fast_finish: true

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.wine

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always

before_install:
  - ulimit -a && free -m

install:
  - sudo $CWD/scripts/provision.sh
  - sudo $CWD/scripts/secur32_fix.sh

before_script:
  - set -e

script:
  - $CWD/scripts/run_backtest.sh $TEST_ARGS
