# Not using Python code, it's just a bone for Travis CI
language: python
python: 3.4

sudo: required
env:
  global:
    - |
      DISPLAY=:0.0
      WINEDLLOVERRIDES="mscoree,mshtml="
      PATH=${PATH//:\.\/node_modules\/\.bin/} # Workaround for Travis issue #4862
      CWD="$TRAVIS_BUILD_DIR"
  matrix:
    - PAIR=EURUSD YEAR=2014 SPREAD=10 BT=DS

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.wine

before_install:
  - ulimit -a
  - ulimit -s 1082768  # Require a bit of more memory.
  - ulimit -a
  - free -m

install:
  - sudo $CWD/scripts/provision.sh

before_script:
  - set -e

script:
  - travis_wait 40 $CWD/scripts/run_backtest.sh -p $PAIR -y $YEAR -s $SPREAD -b $BT
